#!/bin/bash
#
# Wrapper around modified yum 
#

# automatic
export AYUM_DIR=`python -c "from os.path import abspath, dirname; print dirname(abspath('$0'))"`

# ###################
# Configuration
# ###################

# The yum.conf file, take the one from this package by default
export AYUM_CONF=$AYUM_DIR/yum.conf

export PYTHONPATH=$AYM_DIR/src:$PYTHONPATH

# new
$AYUM_DIR/src/yum.private -c $AYUM_CONF  "$@"
