#!/bin/bash
#
# Wrapper around yum --downloadonly plus rpm with private database
#

# automatic
export AYUM_DIR=`python -c "from os.path import abspath, dirname; print dirname(abspath('$0'))"`

# ###################
# Configuration
# ###################
#
# All the following paths can be in completely separate locations
# if necessary.
#

#
# The private RPM database location
# The actual database will be in $AYUM_DBPATH/var/lib/rpm
#
export AYUM_DBPATH=/work/msu-pc7/rhauser/ytest/mydb

# The download cache directory
export AYUM_CACHE=/work/msu-pc7/rhauser/ytest/cache

# Software installation area
export AYUM_INSTALL_AREA=/work/msu-pc7/rhauser/ytest/sw

# The yum.conf file, take the one from this package by default
export AYUM_CONF=$AYUM_DIR/yum.conf

#
# Check for special initdb command
#
if [ "$1" == "initdb" ]
then
    if [ -f $AYUM_DBPATH/var/lib/rpm/__db.001 ]
    then
        echo "RPM database already exists at $AYUM_DBPATH/var/lib/rpm/"
        exit 0
    fi
    mkdir -p $AYUM_DBPATH/var/lib/rpm && rpm --dbpath  $AYUM_DBPATH/var/lib/rpm --initdb
    exit $?
fi

RPM_OPTIONS=""

for arg in $*
do
    case $arg in
        install)
            RPM_OPTIONS=-ihv
            break
            ;;
        update)
            RPM_OPTIONS=-Uhv
            break
            ;;
        remove|erase)
            RPM_OPTIONS=-e
            break
            ;;
        *)
            ;;
    esac
done

rm -f $AYUM_CACHE/*

AYUM_OUT=`mktemp`

$AYUM_DIR/yum.private -c $AYUM_CONF --installroot=$AYUM_DBPATH --downloadonly --downloaddir=$AYUM_CACHE $* | tee $AYUM_OUT

trap 'rm -f $AYUM_OUT' 0

case "${RPM_OPTIONS}" in
    "")
        # nothing to do
        ;;
    -e*)
        # erase
        rpm --dbpath  $AYUM_DBPATH/var/lib/rpm ${RPM_OPTIONS} $(grep '\--->' $AYUM_OUT | awk '{ print $3; }')
        ;;
    *)
        # install or update
        if [ ! -z `/bin/ls $AYUM_CACHE | head -1` ]
        then
            rpm --dbpath $AYUM_DBPATH/var/lib/rpm --prefix=$AYUM_INSTALL_AREA $RPM_OPTIONS $AYUM_CACHE/*
        fi
        ;;
esac
